### ISSUE TITLE
CSS & LESS

### ISSUE THREAD

**Issue by AlexMatusevich** [ilya-markevich/social-chat#1]
Было бы замечательно, чтобы все стили были описаны в едином ключе по каким-либо гайдлайнам. Например, https://wiki.itechart-group.com/pages/viewpage.action?pageId=12779733.

Основные моменты:
1) Не стоит писать единицы измерения, если значением является 0, т.е. например, вместо 0px стоит писать просто 0.
2) Не забывай ставить пробел после открывающей фигурной скобки; где-то он есть, а где-то его не хватает.
3) Не стоит использовать сокращенные hex значения для цветов.
4) Не стоит использовать hex значения в верхнем регистре.
5) Порядок следования CSS свойств стоит унифицировать. Например, в соответствии с приведенными выше стандартами (см. по ссылке), т.е. Positioning, Display, Box Model & Flex Box Model, Visual, Font.
6) Такие значения как 3% выглядят странно.

Устранение вышеупомянутых моментов сделает CSS & LESS код более унифицированным, читабельным, более удобным для внесения изменений со стороны других разработчиков.

**Comment by ilya-markevich** [comment]
Спасибо за подробный комментарий. В ближайшее время пересмотрю свой css

**Comment by AlexMatusevich** [comment]
Не за что :)

**Comment by ilya-markevich** [comment]
Отрефакторил :)
