### ISSUE TITLE
JavaScript: посоветовал бы тебе рассмотреть Backbone.Marionette

### ISSUE THREAD

**Issue by AlexMatusevich** [ilya-markevich/social-chat#10]
В нем уже реализованы некоторые вещи, которые тебе пришлось писать самому. Помимо этого, он обладает дополнительными возможностями, которые могут быть очень полезны и экономят время.

**Comment by ilya-markevich** [comment]
Спасибо, приму к сведению.

**Comment by AlexMatusevich** [comment]
Не за что :)
