### ISSUE TITLE
Node JS: глобальная проблема в архитектуре

### ISSUE THREAD

**Issue by AlexMatusevich** [ilya-markevich/social-chat#11]
У тебя Express приложение создается и стартует только после того, как произойдет подключение к базе, что неправильно. Приложение должно запускаться всегда, а вот в случае ошибки подключения к базе выводить на экран хотя бы какое-нибудь сообщение.

**Comment by ilya-markevich** [comment]
Я смотрел на это с позиции: нет смысла запускать приложение, если неправильно настроена база. Можно считать, что это настройка всего приложения и если она некорректна, то приложение не запускается.

**Comment by AlexMatusevich** [comment]
С одной стороны ты прав, но это не user friendly. Пользователь должен хотя бы понимать, что "пришел по нужному адресу", и видеть хоть какое-то сообщение вместо того, чтобы смотреть на пустое окно и терзать себя сомнениями, а не ошибся ли он местом назначения.

**Comment by ilya-markevich** [comment]
Хороший аргумент, согласен. Сообщение типа "На сайте идут технические работы" :)

**Comment by AlexMatusevich** [comment]
Звучит хорошо :)

**Comment by ilya-markevich** [comment]
Сделал. Также добавил роут на страницу с ошибкой для всех запросов, если коннекшен к базе неправильный.

**Comment by AlexMatusevich** [comment]
Что-то эти изменения после ```git pull``` ко мне "не дошли".

**Comment by ilya-markevich** [comment]
Точно. Буду дома, попробую ещё раз :)

**Comment by AlexMatusevich** [comment]
Хорошо :)

**Comment by ilya-markevich** [comment]
Сделал.
