### ISSUE TITLE
Node JS: ненужная функция-wrapper

### ISSUE THREAD

**Issue by AlexMatusevich** [ilya-markevich/social-chat#13]
room.save(function (err, room) {
    callback(err, room);
})

Достаточно было написать лишь:
room.save(callback);

Да и точки с запятой не хватает.

**Comment by AlexMatusevich** [comment]
В том же файле:

], function (err, room) {
    if (err) return callback(err);
    callback(null, room);
});

Вполне достаточно:
], callback);

**Comment by AlexMatusevich** [comment]
Еще одно место в том же файле:

Room.findOne({'$and': [{isPublic: false}, {users: {'$all': usersIds}}]}, function (err, room) {
    callback(err, room);
});

**Comment by AlexMatusevich** [comment]
Room.findById(roomId, function (err, room) {
    callback(err, room);
});

**Comment by AlexMatusevich** [comment]
], function (err, receivers) {
    callback(err, receivers);
});

**Comment by AlexMatusevich** [comment]
Room.findOne(searchCondition, function (err, room) {
    callback(err, room);
});

**Comment by AlexMatusevich** [comment]
crypto.randomBytes(16, function (err, bytes) {
                callback(err, bytes);
            });

**Comment by AlexMatusevich** [comment]
user.save(function (err, user) {
                callback(err, user);
            });

**Comment by AlexMatusevich** [comment]
], function (err, user) {
        if (err) return callback(err);
        callback(null, user);
    });

**Comment by ilya-markevich** [comment]
Спасибо, буду знать :) Поправил.
