### ISSUE TITLE
Node JS: нецелесообразное использовние тернарного оператора

### ISSUE THREAD

**Issue by AlexMatusevich** [ilya-markevich/social-chat#15]
var searchCondition = isPublicRoom ? {'isPublic': true} : {'$and': [{isPublic: false}, {users: {'$all': usersIds}}]};

Такой код тяжело читать. Лучше использовать старый-добрый if...else :)

**Comment by ilya-markevich** [comment]
Согласен, тяжеловато. Но мне понравилась сама возможность использовать такой код с обычными объектами, но при этом сконструировать запрос :)

**Comment by AlexMatusevich** [comment]
Несколько лет назад меня такие же мысли посещали, но читабельность, как ни крути, важнее.

**Comment by ilya-markevich** [comment]
Изменил.
