### ISSUE TITLE
JavaScript: отсутствует 'use strict'

### ISSUE THREAD

**Issue by AlexMatusevich** [ilya-markevich/social-chat#2]
Отсутствует 'use strict'.

**Comment by ilya-markevich** [comment]
Добавил.

**Comment by AlexMatusevich** [comment]
Отлично.

**Comment by ilya-markevich** [comment]
Возник вопрос: как думаешь, как быть со strict mode в модулях типа:
define({
    START: 'start',
    LOGIN: 'login',
    ROOM_CHANGED: 'roomChanged',
    ROOMS_LOADED: 'roomsLoaded'
});

есть ли смысл его сюда добавлять?

**Comment by ilya-markevich** [comment]
@AlexMatusevich

**Comment by AlexMatusevich** [comment]
В таких случаях, если откинуть унифицированность всего кода, нет смысла добавлять use strict. Но я бы добавил.

**Comment by ilya-markevich** [comment]
Добавил.
