### ISSUE TITLE
JavaScript: строгое стравнение

### ISSUE THREAD

**Issue by AlexMatusevich** [ilya-markevich/social-chat#3]
Если предполагается сравнение между двумя величинами одного типа, то предпочтительнее смотрится строгое сравнение (identity comparison, ===). Обычное сравнение (equality comparison, ==) допустимо в тех случаях, когда предполагается приведение типов при сравнении, что бывает очень редко и далеко не всегда осмысленно.

**Comment by ilya-markevich** [comment]
Согласен, там точно одни типы. Изменил.

**Comment by AlexMatusevich** [comment]
Хорошо :)
