### ISSUE TITLE
JavaScript: неправильное использование typeof

### ISSUE THREAD

**Issue by AlexMatusevich** [ilya-markevich/social-chat#4]
typeof options.disposable === undefined

typeof возвращает результатом строку, а ты используешь строгое сравнение с undefined, что всегда будет возвращать false.

**Comment by ilya-markevich** [comment]
Добавил кавычки :)

**Comment by AlexMatusevich** [comment]
Хорошо :) Также можно было воспользоваться Lodash функцией isUndefined.
