### ISSUE TITLE
JavaScript: enum-ы должны именоваться в PascalCase

### ISSUE THREAD

**Issue by AlexMatusevich** [ilya-markevich/social-chat#7]
urlConstants, customEventsConstants

**Comment by ilya-markevich** [comment]
PascalCase в javascript у меня сразу ассоциируется с функцией конструктором. Погуглив, действительно заметил, что принято использовать PascalCase для enum-ов. Спасибо, буду теперь придерживаться PascalCase.

**Comment by AlexMatusevich** [comment]
Не за что :)

**Comment by ilya-markevich** [comment]
Изменил на PascalCase.

**Comment by AlexMatusevich** [comment]
Отлично :)
