### ISSUE TITLE
JavaScript: имена переменных должны быть понятны

### ISSUE THREAD

**Issue by AlexMatusevich** [ilya-markevich/social-chat#9]
dModel, removeEl и так далее.

При таком именовании ухудшается читабельность кода.

**Comment by ilya-markevich** [comment]
Насчёт dModel соглашусь, можно было бы придумать получше. А removeEl, как мне кажется, в том контексте, где используется, выглядит достаточно ясно.

**Comment by AlexMatusevich** [comment]
По поводу removeEl и подобных имен. Да, согласен, оно понятно, но это не означает, что нужно делать исключения, код должен быть написан в едином ключе и быть максимально читабельным. А что касается длинных имен, то для продакшена нужно использовать минификаторы и подобное.
